include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    public_member_api_docs: ignore

linter:
  rules:
    - library_annotations
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_null_checks_in_equality_operators
